### ISSUE TITLE
Initial deployment issue

### ISSUE THREAD

**Issue by starrchen** [ga-wdi-exercises/project3#33]
I've been trying to deploy our app to Heroku but it's still giving us: 

``` bash
Application Error
An error occurred in the application and your page could not be served. Please try again in a few moments.
If you are the application owner, check your logs for details.
```

I checked our logs and this is the most recent log entry:

``` bash
2015-12-07T19:02:14.625841+00:00 heroku[web.1]: Starting process with command `npm start`
2015-12-07T19:02:18.799717+00:00 app[web.1]: 
2015-12-07T19:02:18.799730+00:00 app[web.1]: > node app.js
2015-12-07T19:02:18.799730+00:00 app[web.1]: 
2015-12-07T19:02:18.799728+00:00 app[web.1]: > project-3@1.0.0 start /app
2015-12-07T19:02:19.986808+00:00 app[web.1]: npm ERR! node v5.1.1
2015-12-07T19:02:19.986082+00:00 app[web.1]: npm ERR! Linux 3.13.0-71-generic
2015-12-07T19:02:19.988111+00:00 app[web.1]: npm ERR! Exit status 1
2015-12-07T19:02:19.898343+00:00 app[web.1]: app listening on port 4000
2015-12-07T19:02:19.930796+00:00 app[web.1]:     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1063:14)
2015-12-07T19:02:19.930785+00:00 app[web.1]: /app/node_modules/mongodb/lib/server.js:235
2015-12-07T19:02:19.930795+00:00 app[web.1]:     at exports._exceptionWithHostPort (util.js:879:20)
2015-12-07T19:02:19.930793+00:00 app[web.1]: Error: connect ECONNREFUSED 127.0.0.1:27017
2015-12-07T19:02:19.987676+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2015-12-07T19:02:19.930794+00:00 app[web.1]:     at Object.exports._errnoException (util.js:856:11)
2015-12-07T19:02:19.930787+00:00 app[web.1]:         process.nextTick(function() { throw err; })
2015-12-07T19:02:19.987910+00:00 app[web.1]: npm ERR! project-3@1.0.0 start: `node app.js`
2015-12-07T19:02:19.997313+00:00 app[web.1]: npm ERR! Tell the author that this fails on your system:
2015-12-07T19:02:19.930780+00:00 app[web.1]: 
2015-12-07T19:02:19.996727+00:00 app[web.1]: npm ERR! Failed at the project-3@1.0.0 start script 'node app.js'.
2015-12-07T19:02:19.986549+00:00 app[web.1]: npm ERR! argv "/app/.heroku/node/bin/node" "/app/.heroku/node/bin/npm" "start"
2015-12-07T19:02:19.997772+00:00 app[web.1]: npm ERR!     npm owner ls project-3
2015-12-07T19:02:19.930788+00:00 app[web.1]:                                       ^
2015-12-07T19:02:19.997606+00:00 app[web.1]: npm ERR! You can get their info via:
2015-12-07T19:02:19.996879+00:00 app[web.1]: npm ERR! Make sure you have the latest version of node.js and npm installed.
2015-12-07T19:02:19.997173+00:00 app[web.1]: npm ERR! not with npm itself.
2015-12-07T19:02:19.997023+00:00 app[web.1]: npm ERR! If you do, this is most likely a problem with the project-3 package,
2015-12-07T19:02:20.012966+00:00 app[web.1]: npm ERR! Please include the following file with any support request:
2015-12-07T19:02:20.012725+00:00 app[web.1]: 
2015-12-07T19:02:19.987441+00:00 app[web.1]: npm ERR! npm  v3.3.12
2015-12-07T19:02:19.997462+00:00 app[web.1]: npm ERR!     node app.js
2015-12-07T19:02:19.966692+00:00 app[web.1]: 
2015-12-07T19:02:19.997899+00:00 app[web.1]: npm ERR! There is likely additional logging output above.
2015-12-07T19:02:20.013097+00:00 app[web.1]: npm ERR!     /app/npm-debug.log
2015-12-07T19:02:19.996656+00:00 app[web.1]: npm ERR! 
2015-12-07T19:02:20.857557+00:00 heroku[web.1]: Process exited with status 1
2015-12-07T19:02:13.119359+00:00 heroku[web.1]: State changed from crashed to starting
2015-12-07T19:02:20.857014+00:00 heroku[web.1]: State changed from starting to crashed
2015-12-07T19:49:53.829372+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=ga-lossary.herokuapp.com request_id=7e3a9640-0470-4203-8eaf-e4619a336639 fwd="50.200.196.50" dyno= connect= service= status=503 bytes=
```

Not sure what's going on here? I thought maybe I should add a `start` to the `package.json` in case the default was not going where it needed to go, but if that was the issue then I definitely did it wrong. :sweat_smile: 

Any insight as to why the app isn't deploying? 

Thanks!

**Comment by RobertAKARobin** [comment]
Have you tried following this tutorial all the way through? I know they want you to do it with just an example repo, but it only takes 10 minutes and is really helpful.

**Comment by starrchen** [comment]
Which tutorial? The Heroku one?

**Comment by RobertAKARobin** [comment]
Oops. Yep: https://devcenter.heroku.com/articles/getting-started-with-nodejs#prepare-the-app . I guess that's a yes?

**Comment by starrchen** [comment]
Mhm, well I mean I got as far as "My app is ready" and then the last step of "Deploy the app" was to run `heroku open` and that's where we've been since.

**Comment by RobertAKARobin** [comment]
Keep on going!

**Comment by RobertAKARobin** [comment]
In particular, pay attention to the part about the Procfile, and this section:

https://devcenter.heroku.com/articles/getting-started-with-nodejs#push-local-changes

``` js
app.set('port', (process.env.PORT || 5000));

//...

app.listen(app.get('port'), function() {
  console.log('Node app is running on port', app.get('port'));
});
```

**Comment by starrchen** [comment]
I keep getting stuck when it comes to actually opening the app (trying to run it locally through `heroku local web` and it doesn't work. :disappointed: )

**Comment by RobertAKARobin** [comment]
Do you get an error?

And you can also always just try going to the next step.

**Comment by starrchen** [comment]
Yeah, it looks like:

``` bash
$ heroku local web
forego | starting web.1 on port 5000
web.1  | { [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
web.1  | js-bson: Failed to load c++ bson extension, using pure JS version
web.1  | events.js:141
```

And on the previous step, it was already indicating a crash. But I might try to forge on and see where it goes?

**Comment by RobertAKARobin** [comment]
Is it actually crashing? I get that same error when running Passport stuff on my local machine and it doesn't prevent the app from working.

**Comment by codedre** [comment]
I am not able to deploy either. I have my Mongolab URI, Procfile, and env with my keys but when I deploy the app crashes because it can not find my env file

**Comment by RobertAKARobin** [comment]
I just deployed to Heroku that "Super Simple Twitter App" from the OAuth class. Take a look at what I changed to make it work:

https://github.com/ga-dc/super-simple-twitter-app/pull/2

https://super-simple-twitter-app.herokuapp.com/

**Comment by codedre** [comment]
Thank you!!!!!!!!!

**Comment by starrchen** [comment]
Hi @RobertAKARobin, so _I_ am still unable to deploy but I'm really glad that @codedre is! :D
